config/routes.rb
BuytCanTho::Application.routes.draw do

  resources :roles_users

  resources :roles

  devise_for :users
  resources :users

  resources :diemtrentuyens do
    member do
      get 'diemtrentuyens_android'
    end
  end

  resources :cokhungthoigians do
    collection do
      post :cokhungtgs_android
    end
  end

  resources :khungthoigians

  resources :gopies do
    collection do
      post 'gopies_android'
      get 'hienthi'
      post 'xuly'
      get 'xoasessiongopy'      
    end
  end

  resources :chuyens do
    collection do
      get 'chuyens_android'
    end
    member do
      get :chuyens_tuyen_android
      get :chuyens_congty_android
      get :chuyens_tram_android
    end
  end

  resources :congties

  resources :diquatrams do
    member do
      get :diquatrams_android
      get :diquatrams_tuyen_android
    end
  end

  resources :tramdungs do
    collection do
      get 'tramdungs_android'
    end
  end

  resources :tuyens do
    collection do
      get 'tuyens_android'
      post 'tuyens_timtheotramdau_android'
      post 'tuyens_timtheotramcuoi_android'
      post 'tuyens_timtheotentuyen_android'
      get 'tuyens_autotext_ten_android'
      get 'tuyens_autotext_ten2_android'
    end
    member do
      get :tuyens_tram_android
      get :tuyens_timtheoma_android

    end
  end

  root :to => 'trangchu#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :roles
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :mact
  # attr_accessible :title, :body
  
  def role?(role)
    return !!self.roles.find_by_name(role.to_s.camelize)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  # GET /users
  # GET /users.json
  def index
    @users = User.paginate(:page => params[:page]).order('email ASC')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form(origin).html.erb
<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= simple_form_for @user, :html => {:class => 'form-horizontal'} do |f| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2>Có <%= pluralize(@user.errors.count, "") %>lỗi :</h2>

          <ul>
            <% @user.errors.values.each do |msg| %>
                <% msg.each do |m| %>
                    <li><%= m %></li>
                <% end %>
            <% end %>
          </ul>
        </div>
    <% end %>


    <table style="margin-left: auto;
            margin-right: auto; ">
      <tr>
        <td>
          <%= f.label "Email: " %>
        </td>
        <td>
          <%= f.text_field :email, :autofocus => true, :disabled => true %>
        </td>
      </tr>
      <tr>
        <td>

            <%= f.label "Công ty:" %>
          </td>
        <td>
            <%= f.select("mact", Congty.order('tenct ASC').all.collect { |c| [c.tenct, c.id] }, {:promt => "Chọn công ty"}, :autofocus => true) %>
        </td>
      </tr>

    </table>
    </br>
    <div class="actions" style="text-align: center">
      <button class="btn btn-primary" type="submit">Lưu</button>
      <%= link_to "Hủy", users_path, :class => 'btn' %>
    </div>
<% end %>

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/index.html.erb
<div class="tieude">
  <h3>TÀI KHOẢN ĐĂNG NHẬP</h3>
</div>


<table class="table">
  <tr>
    <th>Email</th>
    <th>Công ty</th>
    <th>QUYỀN SỬ DỤNG</th>
  </tr>

  <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <%

             @mact = user.mact
             if @mact != nil then
             @congty = Congty.find(@mact)
           end %>

        <% if @mact != nil then %>
            <td><%= @congty.tenct %></td>

        <% else %>
            <td><%= %></td>
        <% end %>

        <% @roles_users = RolesUser.find_by_user_id(user.id)
           if @roles_users != nil then
             @role = Role.find_by_id(@roles_users.role_id) %>
            <td><%= @role.name %></td>
        <% else %>
            <td><%= %></td>
        <% end %>

        <td style="text-align: right">
          <%= link_to user, :class => 'btn  btn-mini btn-info' do %>
              <i class="icon-info-sign"></i>
          <% end %>
          &nbsp;
           <% if can? :update, User %>
               <%= link_to edit_user_path(user), :class => 'btn  btn-mini btn-warning' do %>
                   <i class="icon-pencil"></i>
               <% end %>
           <% end %>
          &nbsp;
          <% if can? :destroy, User %>
              <%= link_to user_path(user), method: :delete, data: {confirm: "Bạn có chắc chắn muốn xóa"}, :class => 'btn  btn-mini btn-danger' do %>
                  <i class="icon-remove"></i>
              <% end %>
          <% end %>
        </td>
      </tr>
  <% end %>
</table>

<br/>

<!-- %= link_to 'Thêm mới', new_user_path, :class => 'btn btn-success' %> -->


<div style=" float: right;" class="flickr_pagination">
  <%= will_paginate @posts %>
</div>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to "Hủy", users_path, :class => 'btn' %>

app/views/users/show.html.erb
<%

   @mact = @user.mact
   if @mact != nil then
     @congty = Congty.find(@mact)
   end
   @roles_users = RolesUser.find_by_user_id(@user.id)
   if @roles_users != nil then
     @role = Role.find_by_id(@roles_users.role_id)
   end %>
<table style="margin-left: auto;
        margin-right: auto;">
  <tr>
    <td>
      <p>
        <b>Email:</b>
        <%= @user.email %>
      </p>
    </td>
  </tr>
  <tr>
    <td>
      <p>
        <b>Công ty:</b>
        <% if @congty != nil then %>
            <%= @congty.tenct %>
        <% end %>
      </p>
    </td>
  </tr>
  <tr>
    <td>
      <p>
        <b>Quyền:</b>
        <% if @role != nil then %>
            <%= @role.name %>
        <% end %>
      </p>
    </td>
  </tr>


  <tr>
    <td>
      <!--
  % if can? :update, Chuyen %>
      %= link_to 'Cập nhật', edit_chuyen_path(@chuyen), :class => 'btn' %> |
  % end %> -->
      <%= link_to 'Quay lại danh sách', users_path, :class => 'btn' %>
    </td>
  </tr>

</table>