config/routes.rb
BuytCanTho::Application.routes.draw do

  resources :roles_users

  resources :roles

  devise_for :users
  resources :users

  resources :diemtrentuyens do
    member do
      get 'diemtrentuyens_android'
    end
  end

  resources :cokhungthoigians do
    collection do
      post :cokhungtgs_android
    end
  end

  resources :khungthoigians

  resources :gopies do
    collection do
      post 'gopies_android'
      get 'hienthi'
      post 'xuly'
      get 'xoasessiongopy'      
    end
  end

  resources :chuyens do
    collection do
      get 'chuyens_android'
    end
    member do
      get :chuyens_tuyen_android
      get :chuyens_congty_android
      get :chuyens_tram_android
    end
  end

  resources :congties

  resources :diquatrams do
    member do
      get :diquatrams_android
      get :diquatrams_tuyen_android
    end
  end

  resources :tramdungs do
    collection do
      get 'tramdungs_android'
    end
  end

  resources :tuyens do
    collection do
      get 'tuyens_android'
      post 'tuyens_timtheotramdau_android'
      post 'tuyens_timtheotramcuoi_android'
      post 'tuyens_timtheotentuyen_android'
      get 'tuyens_autotext_ten_android'
      get 'tuyens_autotext_ten2_android'
    end
    member do
      get :tuyens_tram_android
      get :tuyens_timtheoma_android

    end
  end

  root :to => 'trangchu#index'

end

app/models/diemtrentuyen.rb
# encoding: UTF-8
class Diemtrentuyen < ActiveRecord::Base
  attr_accessible :id, :kinhdo, :matuyen, :vido

  belongs_to :tuyen

  validates :matuyen,
            :presence =>  { :message => "Tuyen không được rỗng"}
  validates :kinhdo,
            :presence =>  { :message => "Kinh do không được rỗng"}
  validates :vido,
            :presence =>  { :message => "Vi do không được rỗng"}

  validates :vido, :uniqueness => {:scope => [:kinhdo, :matuyen],
  :message => 'Dữ liệu này đã bị trùng. Vui lòng chọn giá trị khác cho vĩ độ hoặc kinh độ'}

  self.per_page = 10
end

app/controllers/diemtrentuyens_controller.rb
# encoding: UTF-8
class DiemtrentuyensController < ApplicationController
  authorize_resource
  skip_authorize_resource  :only => [:diemtrentuyens_android]


=begin
  before_filter :authenticate_user!

  before_filter :kiemtra_admin

  def kiemtra_admin
    if current_user.email != 'admin@buytcantho.com' then
      redirect_to root_path
    end
  end
=end

  # GET /diemtrentuyens
  # GET /diemtrentuyens.json
  def index
    @diemtrentuyens = Diemtrentuyen.paginate(:page => params[:page]).order('matuyen ASC')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @diemtrentuyens }
    end
  end

  # GET /diemtrentuyens/1
  # GET /diemtrentuyens/1.json
  def show
    @diemtrentuyen = Diemtrentuyen.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @diemtrentuyen }
    end
  end

  # GET /diemtrentuyens/new
  # GET /diemtrentuyens/new.json
  def new
    @diemtrentuyen = Diemtrentuyen.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @diemtrentuyen }
    end
  end

  # GET /diemtrentuyens/1/edit
  def edit
    @diemtrentuyen = Diemtrentuyen.find(params[:id])
  end

  # POST /diemtrentuyens
  # POST /diemtrentuyens.json
  def create
    @diemtrentuyen = Diemtrentuyen.new(params[:diemtrentuyen])

    respond_to do |format|
      if @diemtrentuyen.save
        format.html { redirect_to @diemtrentuyen, notice: 'Thêm điểm trên tuyến thành công.' }
        format.json { render json: @diemtrentuyen, status: :created, location: @diemtrentuyen }
      else
        format.html { render action: "new" }
        format.json { render json: @diemtrentuyen.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /diemtrentuyens/1
  # PUT /diemtrentuyens/1.json
  def update
    @diemtrentuyen = Diemtrentuyen.find(params[:id])

    respond_to do |format|
      if @diemtrentuyen.update_attributes(params[:diemtrentuyen])
        format.html { redirect_to @diemtrentuyen, notice: 'Cập nhật điểm trên tuyến thành công.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @diemtrentuyen.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /diemtrentuyens/1
  # DELETE /diemtrentuyens/1.json
  def destroy
    @diemtrentuyen = Diemtrentuyen.find(params[:id])
    @diemtrentuyen.destroy

    respond_to do |format|
      format.html { redirect_to diemtrentuyens_url }
      format.json { head :no_content }
    end
  end

  def diemtrentuyens_android
    #@diemtrentuyens  =  Diemtrentuyen.find_all_by_matuyen(params[:id])
    #@diemtrentuyens = Diemtrentuyen.find(:all, :order =>  sort_by('id'))
    @diemtrentuyens  =  Diemtrentuyen.find_all_by_matuyen(params[:id]).sort()
   # @diemtrentuyens.sort_by("id")
    @result = {"success" => 1, "diemtrentuyens" => @diemtrentuyens}
    render :json => @result
  end
end

app/helpers/diemtrentuyens_helper.rb
module DiemtrentuyensHelper
end

app/views/diemtrentuyens/_form.html.erb
<%= simple_form_for @diemtrentuyen, :html => {:class => 'form-horizontal'} do |f| %>

    <% if @diemtrentuyen.errors.any? %>
        <div id="error_explanation">
          <h2>Có <%= pluralize(@diemtrentuyen.errors.count, "") %>lỗi :</h2>

          <ul>
            <% @diemtrentuyen.errors.values.each do |msg| %>
                <% msg.each do |m| %>
                    <li><%= m %></li>
                <% end %>
            <% end %>
          </ul>
        </div>
    <% end %>

    <table style="margin-left: auto;
            margin-right: auto; ">
      <tr>
        <td>

          <div class="field">
            <%= f.label "Tuyến xe: " %>

            <%= f.select("matuyen", Tuyen.all.collect { |c| [c.tentuyen+ " - " + c.tentuyen2, c.matuyen] }, {:promt => "Chọn tuyen"}) %>
          </div>

          <div class="field">
            <%= f.label "Vĩ độ: " %>
            <br/>
            <%= f.text_field :vido %>
          </div>

          <div class="field">
            <%= f.label "Kinh độ: " %>
            <br/>
            <%= f.text_field :kinhdo %>
          </div>
        </td>
      </tr>
    </table>
    </br>

    <div class="actions" style="text-align: center">
      <button class="btn btn-primary" type="submit">Lưu</button>
      <%= link_to "Hủy", diemtrentuyens_path, :class => 'btn' %>
    </div>
<% end %>

app/views/diemtrentuyens/_formedit.html.erb
<%= simple_form_for @diemtrentuyen, :html => {:class => 'form-horizontal'} do |f| %>

    <% if @diemtrentuyen.errors.any? %>
        <div id="error_explanation">
          <h2>Có <%= pluralize(@diemtrentuyen.errors.count, "") %>lỗi :</h2>

          <ul>
            <% @diemtrentuyen.errors.values.each do |msg| %>
                <% msg.each do |m| %>
                    <li><%= m %></li>
                <% end %>
            <% end %>
          </ul>
        </div>
    <% end %>

    <table style="margin-left: auto;
            margin-right: auto; ">
      <tr>
        <td>
          <div class="field">
            <%= f.label "Tuyến xe: " %>

            <%= f.select("matuyen", Tuyen.all.collect { |c| [c.tentuyen+ " - " + c.tentuyen2, c.matuyen] }, {:promt => "Chọn tuyen"}, :disabled => true) %>
          </div>

          <div class="field">
            <%= f.label "Vĩ độ: " %>

            <%= f.text_field :vido %>
          </div>

          <div class="field">
            <%= f.label "Kinh độ: " %>
            <br/>
            <%= f.text_field :kinhdo %>
          </div>
        </td>
      </tr>
    </table>
    </br>

    <div class="actions" style="text-align: center">
      <button class="btn btn-primary" type="submit">Lưu</button>
      <%= link_to "Hủy", diemtrentuyens_path, :class => 'btn' %>
    </div>
<% end %>

app/views/diemtrentuyens/edit.html.erb
<div class="tieude">
  <h3>CẬP NHẬT ĐIỂM TRÊN TUYẾN</h3>
</div>

<%= render 'formedit' %>

app/views/diemtrentuyens/index.html.erb
<div class="tieude">
  <h3>CÁC ĐIỂM TRÊN ĐƯỜNG ĐI CỦA TUYẾN</h3>
</div>



<table class="table">
  <tr>
    <th>Tuyến xe</th>
    <th>Vĩ độ</th>
    <th>Kinh độ</th>
    <th></th>

  </tr>

  <% @diemtrentuyens.each do |diemtrentuyen| %>
      <tr>
        <% @tuyen = Tuyen.find_by_matuyen(diemtrentuyen.matuyen) %>
        <td> [<%= @tuyen.matuyen %>] <%= @tuyen.tentuyen + ' - ' + @tuyen.tentuyen2 %></td>

        <td><%= diemtrentuyen.vido %></td>
        <td><%= diemtrentuyen.kinhdo %></td>
        <td style="text-align: right">
          <%= link_to diemtrentuyen, :class => 'btn  btn-mini btn-info' do %>
              <i class="icon-info-sign"></i>
          <% end %>
          &nbsp;
          <% if can? :update, Diemtrentuyen %>
              <%= link_to edit_diemtrentuyen_path(diemtrentuyen), :class => 'btn  btn-mini btn-warning' do %>
                  <i class="icon-pencil"></i>
              <% end %>
          <% end %>
          &nbsp;
          <% if can? :destroy, Diemtrentuyen %>
              <%= link_to diemtrentuyen_path(diemtrentuyen), method: :delete, data: {confirm: "Bạn có chắc chắn muốn xóa"}, :class => 'btn  btn-mini btn-danger' do %>
                  <i class="icon-remove"></i>
              <% end %>
          <% end %>
        </td>
      </tr>
  <% end %>
</table>

<br/>
<% if can? :new, Diemtrentuyen %>
<%= link_to 'Thêm mới', new_diemtrentuyen_path, :class => 'btn btn-success' %>
<% end %>

<div style=" float: right;" class="flickr_pagination">
  <%= will_paginate @posts %>
</div>

app/views/diemtrentuyens/new.html.erb
<div class="tieude">
  <h3>THÊM ĐIỂM TRÊN TUYẾN</h3>
</div>

<%= render 'form' %>

app/views/diemtrentuyens/show.html.erb
<table style="margin-left: auto;
        margin-right: auto;">
  <tr>
    <td>
      <p>
        <b>Tuyến xe:</b>
        <% @tuyen = Tuyen.find_by_matuyen(@diemtrentuyen.matuyen) %>
        [<%= @tuyen.matuyen %>] <%= @tuyen.tentuyen + ' - ' + @tuyen.tentuyen2 %>
      </p>

      <p>
        <b>Vĩ độ:</b>
        <%= @diemtrentuyen.vido %>
      </p>

      <p>
        <b>Kinh độ:</b>
        <%= @diemtrentuyen.kinhdo %>
      </p>
    </td>
  </tr>

  <tr>
    <td>
      <!--
        %= link_to 'Cập nhật', edit_diemtrentuyen_path(@diemtrentuyen), :class => 'btn' %> |
      -->
      <%= link_to 'Quay lại danh sách', diemtrentuyens_path, :class => 'btn' %>

    </td>
  </tr>

</table>