config/routes.rb
BuytCanTho::Application.routes.draw do

  resources :roles_users

  resources :roles

  devise_for :users
  resources :users

  resources :diemtrentuyens do
    member do
      get 'diemtrentuyens_android'
    end
  end

  resources :cokhungthoigians do
    collection do
      post :cokhungtgs_android
    end
  end

  resources :khungthoigians

  resources :gopies do
    collection do
      post 'gopies_android'
      get 'hienthi'
      post 'xuly'
      get 'xoasessiongopy'      
    end
  end

  resources :chuyens do
    collection do
      get 'chuyens_android'
    end
    member do
      get :chuyens_tuyen_android
      get :chuyens_congty_android
      get :chuyens_tram_android
    end
  end

  resources :congties

  resources :diquatrams do
    member do
      get :diquatrams_android
      get :diquatrams_tuyen_android
    end
  end

  resources :tramdungs do
    collection do
      get 'tramdungs_android'
    end
  end

  resources :tuyens do
    collection do
      get 'tuyens_android'
      post 'tuyens_timtheotramdau_android'
      post 'tuyens_timtheotramcuoi_android'
      post 'tuyens_timtheotentuyen_android'
      get 'tuyens_autotext_ten_android'
      get 'tuyens_autotext_ten2_android'
    end
    member do
      get :tuyens_tram_android
      get :tuyens_timtheoma_android

    end
  end

  root :to => 'trangchu#index'

end

app/models/tuyen.rb
# encoding: UTF-8
class Tuyen < ActiveRecord::Base
  attr_accessible :culy, :giancach, :id, :loaihinh, :matuyen, :sochuyen,
                  :tentuyen, :tghoatdong, :thoigianchuyen, :tentuyen2

  has_many :diquatram
  has_many :chuyen
  has_many :diemtrentuyen

  validates :matuyen,
            :presence => {:message => "Mã tuyến không được rỗng"}
  validates :tentuyen,
            :presence => {:message => "Điểm xuất phát không được rỗng"}
  validates :tentuyen2,
            :presence => {:message => "Đích đến không được rỗng"}
  validates :culy,
            :presence => {:message => "Cự ly không được rỗng"}
  validates :giancach,
            :presence => {:message => "Giãn cách không được rỗng"}
  validates :loaihinh,
            :presence => {:message => "Loại hình không được rỗng"}
  validates :sochuyen,
            :presence => {:message => "Số chuyến không được rỗng"}
  validates :sochuyen,
            :numericality => {:only_integer => true, :greater_than => 0,
                              :message => "Số chuyến phải là số nguyên dương"}
  validates :thoigianchuyen,
            :numericality => {:only_integer => true, :greater_than => 0,
                              :message => "Thời gian chuyến phải là số nguyên dương"}
  validates :giancach,
            :numericality => {:only_integer => true, :greater_than => 0,
                              :message => "Giãn cách phải là số nguyên dương"}
  validates :culy,
            :numericality => {:only_integer => true, :greater_than => 0,
                              :message => "Cự ly phải là số nguyên dương"}

  validates :matuyen,
            :numericality => {:only_integer => true, :greater_than => 0,
                              :message => "Mã tuyến phải là số nguyên dương"}

  self.per_page = 10

end

app/controllers/tuyens_controller.rb
# encoding: UTF-8
class TuyensController < ApplicationController
  authorize_resource
  skip_authorize_resource :only => [:index, :show, :tuyens_android, :tuyens_timtheotramcuoi_android,
                                    :tuyens_timtheotramdau_android, :tuyens_timtheoma_android, :tuyens_tram_android,
                                    :tuyens_timtheotentuyen_android, :tuyens_autotext_ten_android, :tuyens_autotext_ten2_android]


  #before_filter :authenticate_user!, :kiemtra_quyen, :except => [:tuyens_tram_android,
  #                                              :tuyens_timtheoma_android, :tuyens_timtheotramdau_android,
  #                                              :tuyens_timtheotramcuoi_android, :tuyens_android]

  def kiemtra_quyen
    if  user_signed_in?
      if current_user.admin == 1 then
        session[:quyen] = 'admin'
      else
        @taikhoan = Taikhoan.find_by_tentk(current_user.email);

        if @taikhoan == nil
          session[:quyen] = 'khach'
        else
          session[:quyen] = 'congty'
        end
      end
    else
      session[:quyen] = 'khach'
    end
  end


  # GET /tuyens
  # GET /tuyens.json
  def index
    @tuyens = Tuyen.paginate(:page => params[:page]).order('matuyen ASC')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tuyens }
    end
  end


  # GET /tuyens/1
  # GET /tuyens/1.json
  def show
    @tuyen = Tuyen.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tuyen }
    end
  end

  # GET /tuyens/new
  # GET /tuyens/new.json
  def new
    @tuyen = Tuyen.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tuyen }
    end
  end

  # GET /tuyens/1/edit
  def edit
    @tuyen = Tuyen.find(params[:id])
  end

  # POST /tuyens
  # POST /tuyens.json
  def create
    @tuyen = Tuyen.new(params[:tuyen])

    respond_to do |format|
      if @tuyen.save
        format.html { redirect_to @tuyen, notice: 'Thêm tuyến thành công.' }
        format.json { render json: @tuyen, status: :created, location: @tuyen }
      else
        format.html { render action: "new" }
        format.json { render json: @tuyen.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tuyens/1
  # PUT /tuyens/1.json
  def update
    @tuyen = Tuyen.find(params[:id])

    respond_to do |format|
      if @tuyen.update_attributes(params[:tuyen])
        format.html { redirect_to @tuyen, notice: 'Cập nhật tuyến thành công.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tuyen.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tuyens/1
  # DELETE /tuyens/1.json
  def destroy
    @tuyen = Tuyen.find(params[:id])
    @tuyen.destroy

    respond_to do |format|
      format.html { redirect_to tuyens_url }
      format.json { head :no_content }
    end
  end

  def tuyens_android
    @tuyens = Tuyen.order('matuyen ASC').all
    result = {"success" => 1, "tuyens" => @tuyens}
    #result = []#{name: @tuyens.first.culy}
    #@tuyens.each do |tuyen|
    # result << {"culy" => tuyen.culy}
    #end
    render :json => result
    #render :json =>
    #render :json => @tuyens
    #respond_to do |format|
    # format.html # index.html.erb
    #  format.json { render :json => @tuyens }
    #end

  end


  def tuyens_tram_android
    @diquatrams = Diquatram.order('matuyen ASC').find_all_by_matram(params[:id])
    @tuyens = Array.new

    @diquatrams.each do |d|
      @tuyen = Tuyen.find_by_matuyen(d.matuyen)
      @tuyens.append(@tuyen)
    end

    @result = {"success" => 1, "tuyens" => @tuyens}
    render :json => @result
  end

  def tuyens_timtheoma_android
    #@tuyens = nil
    puts "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    @tuyens = Tuyen.order('matuyen ASC').find_all_by_matuyen(params[:id])


      @result = {"success" => "1", "tuyens" => @tuyens}

    render :json => @result
  end

  def tuyens_timtheotramdau_android
    puts "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    #puts params[:id]
    @tuyens = Tuyen.order('matuyen ASC').find_all_by_tentuyen(params[:id])

    @result = {"success" => "1", "tuyens" => @tuyens}
    render :json => @result
  end

  def tuyens_timtheotramcuoi_android
    #puts "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    #puts params[:id]
    @tuyens = Tuyen.order('matuyen ASC').find_all_by_tentuyen2(params[:id])

    @result = {"success" => "1", "tuyens" => @tuyens}
    render :json => @result
  end
  
  def tuyens_timtheotentuyen_android
    puts "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    puts params[:tentuyen]
    puts params[:tentuyen2]
    @tuyens = Tuyen.order("matuyen ASC").where(:tentuyen => params[:tentuyen]).where(:tentuyen2 => params[:tentuyen2]).first 
    #@tuyens = Tuyen.find_by_id("1")
    #@tuyens = Tuyen.all
    
    @result = {"success" => "1", "tuyens" => @tuyens}
    render :json => @result
  end
  
  def tuyens_autotext_ten_android
    @tuyens = Tuyen.order('tentuyen ASC').select('tentuyen as tentuyen').uniq
    result = {"success" => 1, "tuyens" => @tuyens}
    render :json => result
  end
  
  def tuyens_autotext_ten2_android
    @tuyens = Tuyen.order('tentuyen2 ASC').select('tentuyen2 as tentuyen2').uniq
    result = {"success" => 1, "tuyens" => @tuyens}
    render :json => result
  end

end

app/helpers/tuyens_helper.rb
module TuyensHelper
end

app/views/tuyens/_form.html.erb
<%= simple_form_for @tuyen, :html => {:class => 'form-horizontal'} do |f| %>
    <% if @tuyen.errors.any? %>
        <div id="error_explanation">
          <h2>Có <%= pluralize(@tuyen.errors.count, "") %>lỗi :</h2>

          <ul>
            <% @tuyen.errors.values.each do |msg| %>
                <% msg.each do |m| %>
                    <li><%= m %></li>
                <% end %>
            <% end %>
          </ul>
        </div>
    <% end %>





    <table style="margin-left: auto;
            margin-right: auto; ">
      <tr>
        <td>
          <div class="field">
            <%= f.label"Mã tuyến:" %>
            <br/>
            <%= f.number_field :matuyen %>
          </div>
        </td>
        <td>
          <div class="field">
            <%= f.label"Nơi Xuất Phát:" %>
            <br/>
            <%= f.text_field :tentuyen %>
          </div>
        </td>
        <td>
          <div class="field">
            <%= f.label"Đích:" %>
            <br/>
            <%= f.text_field :tentuyen2 %>
          </div>
        </td>
      </tr>

      <tr>
        <td>
          <div class="field">
            <%= f.label"Loại hình:" %>
            <br/>
            <%= f.text_field :loaihinh %>
          </div>
        </td>
        <td>
          <div class="field">
            <%= f.label"Cự ly (km):" %>
            <br/>
            <%= f.number_field :culy %>
          </div>
        </td>
        <td>
          <div class="field">
            <%= f.label"Số chuyến:" %>
            <br/>
            <%= f.number_field :sochuyen %>
          </div>
        </td>
      </tr>
      <tr>
        <td>
          <div class="field">
            <%=f.label "T/gian tuyến (phút):" %>
            <br/>
            <%= f.number_field :thoigianchuyen %>
          </div>
        </td>
        <td>
          <div class="field">
            <%=f.label "Giãn cách (phút):" %>
            <br/>
            <%= f.number_field :giancach %>
          </div>
        </td>
        <td>
          <div class="field">
            <%=f.label "Thời gian hoạt động:" %>
            <br/>
            <%= f.text_field :tghoatdong %>
          </div>
        </td>
      </tr>
    </table>
    </br>

    <div class="actions" style="text-align: center">
      <button class="btn btn-primary" type="submit">Lưu</button>
      <%= link_to "Hủy", tuyens_path, :class => 'btn' %>
    </div>

<% end %>

app/views/tuyens/_formedit.html.erb
<%= simple_form_for @tuyen, :html => {:class => 'form-horizontal'} do |f| %>
    <% if @tuyen.errors.any? %>
        <div id="error_explanation">
          <h2>Có <%= pluralize(@tuyen.errors.count, "") %>lỗi :</h2>

          <ul>
            <% @tuyen.errors.values.each do |msg| %>
                <% msg.each do |m| %>
                    <li><%= m %></li>
                <% end %>
            <% end %>
          </ul>
        </div>
    <% end %>

    <table style="margin-left: auto;
            margin-right: auto; border-spacing: 50px 50px; text-align: left">
      <tr>
        <td>
          <div class="field">
            <%= f.label"Mã tuyến:" %>
            <br/>
            <%= f.number_field :matuyen, :disabled => true %>
          </div>
        </td>
        <td>
          <div class="field">
            <%= f.label"Nơi Xuất Phát:" %>
            <br/>
            <%= f.text_field :tentuyen %>
          </div>
        </td>
        <td>
          <div class="field">
            <%= f.label"Đích:" %>
            <br/>
            <%= f.text_field :tentuyen2 %>
          </div>
        </td>
      </tr>

      <tr>
        <td>
          <div class="field">
            <%= f.label"Loại hình:" %>
            <br/>
            <%= f.text_field :loaihinh %>
          </div>
        </td>
        <td>
          <div class="field">
            <%= f.label"Cự ly (km):" %>
            <br/>
            <%= f.number_field :culy %>
          </div>
        </td>
        <td>
          <div class="field">
            <%= f.label"Số chuyến:" %>
            <br/>
            <%= f.number_field :sochuyen %>
          </div>
        </td>
      </tr>
      <tr>
        <td>
          <div class="field">
            <%=f.label "T/gian tuyến (phút):" %>
            <br/>
            <%= f.number_field :thoigianchuyen %>
          </div>
        </td>
        <td>
          <div class="field">
            <%=f.label "Giãn cách (phút):" %>
            <br/>
            <%= f.number_field :giancach %>
          </div>
        </td>
        <td>
          <div class="field">
            <%=f.label "Thời gian hoạt động:" %>
            <br/>
            <%= f.text_field :tghoatdong %>
          </div>
        </td>
      </tr>
    </table>

    <div class="actions" style="text-align: center">
      <button class="btn btn-primary" type="submit">Lưu</button>
      <%= link_to "Hủy", tuyens_path, :class => 'btn' %>
    </div>
<% end %>

app/views/tuyens/edit.html.erb
<div class="tieude">
  <h3>CẬP NHẬT THÔNG TIN TUYẾN XE</h3>
</div>


<%= render 'formedit' %>

app/views/tuyens/index.html.erb
<div class="tieude">
  <h3>TUYẾN XE</h3>
</div>



<table class="table ">
  <tr>
    <th>Mã tuyến</th>
    <th>Tên tuyến</th>
    <th>Loại hình</th>
    <th>Cự ly (km)</th>
    <th></th>
  </tr>

  <% @tuyens.each do |tuyen| %>
      <tr>
        <td><%= tuyen.matuyen %></td>
        <td><%= tuyen.tentuyen + " - " + tuyen.tentuyen2 %></td>
        <td><%= tuyen.loaihinh %></td>
        <td><%= tuyen.culy %></td>
        <% if session[:quyen] != 'khach' %>
            <td style="text-align: right">
              <%= link_to tuyen, :class => 'btn  btn-mini btn-info' do %>
                  <i class="icon-info-sign"></i>
              <% end %>

              &nbsp;
<% if can? :update, Tuyen %>
              <%= link_to edit_tuyen_path(tuyen), :class => 'btn  btn-mini btn-warning' do %>
                  <i class="icon-pencil"></i>
              <% end %>
<% end %>

              &nbsp;
<% if can? :destroy, Tuyen %>
              <%= link_to tuyen_path(tuyen), method: :delete, data: {confirm: "Bạn có chắc chắn muốn xóa"}, :class => 'btn  btn-mini btn-danger' do %>
                  <i class="icon-remove"></i>
              <% end %>
<% end %>
            </td>
        <% end %>
      </tr>
  <% end %>
</table>

<br/>
<% if can? :new , Tuyen %>
<%= link_to 'Thêm mới', new_tuyen_path, :class => 'btn btn-success' %>
<% end %>

<div style=" float: right;" class="flickr_pagination">
  <%= will_paginate @posts %>
</div>

app/views/tuyens/new.html.erb
<div class="tieude">
  <h3>THÊM TUYẾN XE</h3>
</div>

<%= render 'form' %>

app/views/tuyens/show.html.erb
<table style="margin-left: auto;
        margin-right: auto;">
  <tr>
    <td>
      <p>
        <b>Mã tuyến:</b>
        <%= @tuyen.matuyen %>
      </p>

      <p>
        <b>Tên tuyến:</b>
        <%= @tuyen.tentuyen + " - " + @tuyen.tentuyen2 %>
      </p>

      <p>
        <b>Loại hình:</b>
        <%= @tuyen.loaihinh %>
      </p>

      <p>
        <b>Cự ly:</b>
        <%= @tuyen.culy %> km
      </p>

      <p>
        <b>Số chuyến:</b>
        <%= @tuyen.sochuyen %>
      </p>

      <p>
        <b>Thời gian tuyến:</b>
        <%= @tuyen.thoigianchuyen %> phút
      </p>

      <p>
        <b>Giãn cách:</b>
        <%= @tuyen.giancach %>  phút
      </p>

      <p>
        <b>Thời gian hoạt động:</b>
        <%= @tuyen.tghoatdong %>
      </p>
    </td>
  </tr>

  <tr>
    <td>
	<!--
      %= link_to 'Cập nhật', edit_tuyen_path(@tuyen), :class => 'btn' %> |
      -->
<%= link_to 'Quay lại danh sách', tuyens_path, :class => 'btn' %>
    </td>
  </tr>

</table>