config/routes.rb
BuytCanTho::Application.routes.draw do

  resources :roles_users

  resources :roles

  devise_for :users
  resources :users

  resources :diemtrentuyens do
    member do
      get 'diemtrentuyens_android'
    end
  end

  resources :cokhungthoigians do
    collection do
      post :cokhungtgs_android
    end
  end

  resources :khungthoigians

  resources :gopies do
    collection do
      post 'gopies_android'
      get 'hienthi'
      post 'xuly'
      get 'xoasessiongopy'      
    end
  end

  resources :chuyens do
    collection do
      get 'chuyens_android'
    end
    member do
      get :chuyens_tuyen_android
      get :chuyens_congty_android
      get :chuyens_tram_android
    end
  end

  resources :congties

  resources :diquatrams do
    member do
      get :diquatrams_android
      get :diquatrams_tuyen_android
    end
  end

  resources :tramdungs do
    collection do
      get 'tramdungs_android'
    end
  end

  resources :tuyens do
    collection do
      get 'tuyens_android'
      post 'tuyens_timtheotramdau_android'
      post 'tuyens_timtheotramcuoi_android'
      post 'tuyens_timtheotentuyen_android'
      get 'tuyens_autotext_ten_android'
      get 'tuyens_autotext_ten2_android'
    end
    member do
      get :tuyens_tram_android
      get :tuyens_timtheoma_android

    end
  end

  root :to => 'trangchu#index'

end

app/models/tramdung.rb
# encoding: UTF-8
class Tramdung < ActiveRecord::Base
  attr_accessible :diachitram, :id, :matram, :tentram, :vido, :kinhdo

  has_many :diquatram

  validates :tentram,
            :presence => {:message => "Tên trạm không được rỗng"}
  validates :diachitram,
            :presence => {:message => "Địa chỉ trạm không được rỗng"}

  self.per_page = 10

end

app/controllers/tramdungs_controller.rb
# encoding: UTF-8
class TramdungsController < ApplicationController
  authorize_resource
  skip_authorize_resource  :only => [:index, :show, :tramdungs_android]

=begin
  before_filter :authenticate_user!

  before_filter :kiemtra_admin

  def kiemtra_admin
    if current_user.email != 'admin@buytcantho.com' then
      redirect_to root_path
    end
  end
=end

  # GET /tramdungs
  # GET /tramdungs.json
  def index
    @tramdungs = Tramdung.paginate(:page => params[:page]).order('tentram ASC')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tramdungs }
    end
  end


  # GET /tramdungs/1
  # GET /tramdungs/1.json
  def show
    @tramdung = Tramdung.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tramdung }
    end
  end

  # GET /tramdungs/new
  # GET /tramdungs/new.json
  def new
    @tramdung = Tramdung.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tramdung }
    end
  end

  # GET /tramdungs/1/edit
  def edit
    @tramdung = Tramdung.find(params[:id])
  end

  # POST /tramdungs
  # POST /tramdungs.json
  def create
    @tramdung = Tramdung.new(params[:tramdung])

    respond_to do |format|
      if @tramdung.save
        format.html { redirect_to @tramdung, notice: 'Thêm trạm dừng thành công.' }
        format.json { render json: @tramdung, status: :created, location: @tramdung }
      else
        format.html { render action: "new" }
        format.json { render json: @tramdung.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tramdungs/1
  # PUT /tramdungs/1.json
  def update
    @tramdung = Tramdung.find(params[:id])

    respond_to do |format|
      if @tramdung.update_attributes(params[:tramdung])
        format.html { redirect_to @tramdung, notice: 'Cập nhật trạm dừng thành công.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tramdung.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tramdungs/1
  # DELETE /tramdungs/1.json
  def destroy
    @tramdung = Tramdung.find(params[:id])
    @tramdung.destroy

    respond_to do |format|
      format.html { redirect_to tramdungs_url }
      format.json { head :no_content }
    end
  end

  def tramdungs_android
    @tramdungs = Tramdung.all

    result = {"success" => 1, "tramdungs" => @tramdungs}
    render :json => result

  end
end

app/helpers/tramdungs_helper.rb
module TramdungsHelper
end

app/views/tramdungs/_form.html.erb
<%= simple_form_for @tramdung, :html => {:class => 'form-horizontal'} do |f| %>
    <% if @tramdung.errors.any? %>
        <div id="error_explanation">
          <h2>Có <%= pluralize(@tramdung.errors.count, "") %>lỗi :</h2>

          <ul>
            <% @tramdung.errors.values.each do |msg| %>
                <% msg.each do |m| %>
                    <li><%= m %></li>
                <% end %>
            <% end %>
          </ul>
        </div>
    <% end %>

    <table style="margin-left: auto;
            margin-right: auto; ">
      <tr>
        <td>

          <div class="field">
            <%= f.label "Tên trạm:" %>

            <%= f.text_field :tentram %>
          </div>
          <div class="field">
            <%= f.label "Địa chỉ:" %>
            <br/>
            <%= f.text_field :diachitram %>
          </div>
          <div class="field">
            <%= f.label "Vĩ độ:" %>
            <br/>
            <%= f.text_field :vido %>
          </div>
          <div class="field">
            <%= f.label "Kinh độ:" %>
            <br/>
            <%= f.text_field :kinhdo %>
          </div>
        </td>
      </tr>
    </table>
    </br>
    <div class="actions" style="text-align: center">
      <button class="btn btn-primary" type="submit">Lưu</button>
      <%= link_to "Hủy", tramdungs_path, :class => 'btn' %>
    </div>
<% end %>

app/views/tramdungs/edit.html.erb
<div class="tieude">
  <h3>CẬP NHẬT THÔNG TIN TRẠM DỪNG</h3>
</div>

<%= render 'form' %>

app/views/tramdungs/index.html.erb
<div class="tieude">
  <h3>TRẠM DỪNG</h3>
</div>




<table  class="table ">
  <tr>
    <th>Tên trạm dừng</th>
    <th>Địa chỉ</th>
    <th></th>

  </tr>

<% @tramdungs.each do |tramdung| %>
  <tr>
    <td><%= tramdung.tentram %></td>
    <td><%= tramdung.diachitram %></td>
    <td style="text-align: right">
      <%= link_to tramdung, :class => 'btn  btn-mini btn-info' do %>
          <i class="icon-info-sign"></i>
      <% end %>
      &nbsp;
<% if can? :update, Tramdung %>
      <%= link_to edit_tramdung_path(tramdung), :class => 'btn  btn-mini btn-warning' do %>
          <i class="icon-pencil"></i>
      <% end %>
<% end %>
      &nbsp;
<% if can? :destroy, Tramdung %>
      <%= link_to tramdung_path(tramdung), method: :delete, data: {confirm: "Bạn có chắc chắn muốn xóa"}, :class => 'btn  btn-mini btn-danger' do %>
          <i class="icon-remove"></i>
      <% end %>
<% end %>
    </td>
  </tr>
<% end %>
</table>

<br />

<% if can? :destroy, Tramdung %>
<%= link_to 'Thêm mới', new_tramdung_path, :class =>'btn btn-success' %>
<% end %>

<div style=" float: right;" class="flickr_pagination">
  <%= will_paginate @posts %>
</div>

app/views/tramdungs/new.html.erb
<div class="tieude">
  <h3>THÊM TRẠM DỪNG</h3>
</div>

<%= render 'form' %>

app/views/tramdungs/show.html.erb
<table style="margin-left: auto;
        margin-right: auto;">
  <tr>
    <td>
      <p>
        <b>Tên trạm:</b>
        <%= @tramdung.tentram %>
      </p>

      <p>
        <b>Địa chỉ:</b>
        <%= @tramdung.diachitram %>
      </p>

      <p>
        <b>Vĩ độ:</b>
        <%= @tramdung.vido %>
      </p>

      <p>
        <b>Kinh độ:</b>
        <%= @tramdung.kinhdo %>
      </p>
    </td>
  </tr>

  <tr>
    <td>
<!--
      %= link_to 'Cập nhật', edit_tramdung_path(@tramdung), :class => 'btn' %> |
-->    
  <%= link_to 'Quay lại danh sách', tramdungs_path, :class => 'btn' %>
    </td>
  </tr>

</table>